server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
